title: Jaeyeon.Park # name of the site
author: Jaeyeon Park # name of site's author
email: ok6530@snu.ac.kr # email of site's author
url: https://jaeyeon302.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Being the sea that embraces all life.  <br/>

  

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# theme: no-style-please
remote_theme: jaeyeon302/jaeyeon302.github.io  # if you are using GitHub Pages

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "‚Üê" # customize text for homepage link in post layout
  date_format_YM: "%Y-%m"
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
